name = "plant_api"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "A simple API for managing evolving digital pets"
licences = ["Apache-2.0"]
repository = { type = "github", user = "sneakycrow", repo = "gleam-plant-api" }
links = [
    { title = "Website", href = "https://sneakycrow.dev/lib/gleam-plant-api" },
]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
mist = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_otp = ">= 0.10.0 and < 1.0.0"
gleam_pgo = ">= 0.7.0 and < 1.0.0"
argv = ">= 1.0.2 and < 2.0.0"
simplifile = ">= 1.7.0 and < 2.0.0"
birl = ">= 1.6.1 and < 2.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
envoy = ">= 1.0.1 and < 2.0.0"
lustre = ">= 4.2.2 and < 5.0.0"
wisp = ">= 0.14.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
